title: Mess Application
description: Documentation for Mess App

remote_theme: just-the-docs/just-the-docs

url: "https://muragesh-24.github.io"
baseurl: "/Mess-App-Docshow"

plugins:
  - jekyll-remote-theme

aux_links:
  GitHub Repo: https://github.com/Muragesh-24/Mess-App-Docs
  
