title: Mess Application
description: Documentation for Mess Application

theme: just-the-docs

url: "https://muragesh-24.github.io"
baseurl: "/Mess-App-Docshow"

aux_links:
  GitHub Repo: https://github.com/Muragesh-24/Mess-App-Docshow
